name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu çek
      uses: actions/checkout@v3

    - name: .NET SDK kurulumu
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'  # Projene göre değiştir

    - name: Bağımlılıkları yükle
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test ve Coverage
      run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

    - name: Coverage raporunu yükle
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: '**/TestResults/**/*.xml'
