// Assembly attributes are generated by the SDK for .NET 8 and newer. Keep these only for older targets.
#if !NET8_0
using System.Reflection;

[assembly: AssemblyTitle("KesifUygulamasiTemplate.Tests")]
[assembly: AssemblyProduct("KesifUygulamasiTemplate.Tests")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
#endif
